Full history GPT discussion
ardium-pl/GWW-Legal pull request #51
Opened 2024-08-02 11:52 UTC by WolnyMikolaj

2024-08-02 12:14 UTC, joker876 requested changes

2024-08-02 12:14 UTC, joker876 commented on server/api/router.js
> +  }
ten fragment dosłownie nic nie robi. Bez `catch`a error i tak pojawiłby się w konsoli, a client otrzymałby dokładnie taki sam response.

2024-08-02 12:14 UTC, joker876 commented on server/api/router.js
> +  }
ta funkcja powinna albo być utworzona gdzieś poza obsługą zapytania, najlepiej w osobnym pliku utilsowym, albo logika tej funkcji powinna po prostu zostać przeniesiona od razu tam, gdzie jest użyta, bez tworzenia dodatkowej funkcji (preferowana opcja 1)

2024-08-05 18:53 UTC, Szymon-Skowron commented on server/api/router.js
> +  }
Przekopiowałem ten blok kodu z endpointa wyżej (linijki 69-72), uznałem że skoro tam mieliście tak napisane, to że będzie dobrze, gdy tez tak napisze.

2024-08-05 19:00 UTC, Szymon-Skowron commented on server/api/router.js
> +  }
Funkcja została przeniesiona do pliku nsaMain.js, w którym z tego co widze macie inne podobne funkcje, które stamtąd eksportujecie.

2024-08-05 22:32 UTC, joker876 commented on server/api/router.js
> +  }
Dobra, to zostaw

2024-08-05 22:33 UTC, joker876 approved these changes

2024-08-20 21:18 UTC, merged