Added full data base handeling
ardium-pl/GWW-Legal pull request #8
Opened 2024-05-28 05:39 UTC by WolnyMikolaj

2024-05-28 15:05 UTC, joker876 commented on server/sql/messagesQuerry.js
> +        return false;
I jeszcze trochę nie rozumiem dlaczego w tych funkcjach jest co chwile zwracane `false`?

2024-06-29 16:36 UTC, joker876 requested changes

2024-06-29 16:36 UTC, joker876 commented on server/api/router.js
> +    const caseSignature = await getSignatureByContent(courtRuling);
Na pewno nie może tak być że wyszukujemy sygnaturę po zawartości. Jeśli potrzebujesz sygnatury to prześlij ją z clienta, a nie wyszukuj w bazie.

2024-06-30 22:32 UTC, WolnyMikolaj commented on server/api/router.js
> +    const caseSignature = await getSignatureByContent(courtRuling);
Done

2024-06-30 22:32 UTC, WolnyMikolaj commented on server/sql/messagesQuerry.js
> +        return false;
Done

2024-06-30 22:33 UTC, WolnyMikolaj commented on server/api/router.js
> +    const response = await getOrSetGptResponse(courtRulingID, systemMessageID, userMessageID) || await askGptAboutNSA(systemMessage, userMessage, courtRuling, caseSignature);
Sory ale Prettier m się spieprzył i na razie nie wiem jak go naprawić. Podzieliłem ręcznie ten fragment, żeby zwiększyć czytelność  

![image](https://github.com/ardium-pl/GWW-Legal/assets/136742392/d81b4c74-d520-47f4-8cd9-43428baf10bc)

2024-07-11 08:45 UTC, joker876 requested changes

2024-07-11 08:45 UTC, joker876 commented on server/api/nsaMain.js
> +  }
sqlowe polecenie `INSERT` zwraca obiekt: 
![image](https://github.com/ardium-pl/GWW-Legal/assets/42680429/2e137d81-6e89-4ef0-8934-b34588fd3187)
z tego obiektu można wyciągnąć `insertId`, dzięki czemu nie trzeba ponownie obciążać bazy danych dodatkowym zapytaniem wyszukania.

Funkcje insert są do przerobienia, aby zwracały id dodanego rekordu, a funkcje get są do usunięcia w tym miejscu.

2024-07-11 08:45 UTC, joker876 commented on server/sql/courtRulingQuerry.js
> +}
Nieużywana funkcja do usunięcia.

2024-07-11 23:02 UTC, WolnyMikolaj commented on server/api/nsaMain.js
> +  }
Czy zamiast przerabiać inswerty nie mogę po prostu zrobić czegoś takiego:
![image](https://github.com/user-attachments/assets/8efdcebf-21d6-4be8-b572-fe65c1959ff3)

2024-07-12 06:02 UTC, joker876 approved these changes

2024-07-12 10:37 UTC, joker876 approved these changes

2024-07-12 10:37 UTC, merged